numpy

********************

In [50]:
import numpy as np

In [51]:
# Create a list
# np = numpy

L = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [52]:
L

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
print (L)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
L = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)

In [55]:
print(L)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [56]:
L.dtype

dtype('float64')

In [57]:
# It'll generate a random number.
# It'll include the low number(1), but it won't include the high number (7)

np.random.randint(1, 7)

1

In [58]:
# Roll a dice.
rolls = np.random.randint(1, 7, 1000)

In [59]:
# Average roll.

np.mean(rolls)

3.575

In [60]:
# Spread
# Standar deviation

np.std(rolls)

1.707739734268662

In [61]:
# likert scale. 
likert = np.random.randint(1, 8, 1000)

In [62]:
np.mean(likert)

4.017

In [63]:
# Median value

np.median(likert)

4.0